### ISSUE TITLE
How to define the positive and negative classes for the subtyping task

### ISSUE THREAD

**Issue by HHHedo** [ChongQingNoSubway/DGR-MIL#3]
Hi, 
Thanks for your great work!
I have one simple question: How to define the positive and negative classes for the subtyping task? Especially, when the number of classes is over 2.

Best,
Tiancheng

**Comment by ChongQingNoSubway** [comment]
Hello Tiancheng,
Thanks for your interest!
The negative and positive classes are the cases where the bag labels are 0 and 1. 

If still under the semantics of MIL, it is converted to a multilabel classification problem. Still, the same NEGATIVE CENTER is updated only if the bag label is 0, and the rest of the labels update the POSITIVE CENTER. 

But if it is a strict one-hot classification problem, you should assign a center to each class.

Here are my current thoughts on multi-label classification task, which could be explored further

**Comment by HHHedo** [comment]
Thanks for your kind help!
For NSCLC (LUAD vs. LUSC), when I change the labels (i.e., LUAD=0, LUSC=1/LUAD=1, LUSC=0), the performance also changes. Please advise us on how to define the labels since I think the alignment loss is a bit confusing in this situation.

**Comment by ChongQingNoSubway** [comment]
If you change the label here, it is possible that the LUAD and Lusc's DIVERSITY is different because the DIVERSITY of the POSITIVE instance is learned through the global tokens, which is likely to result in a change in performance in the same number of global tokens. (Adjusting the number of global may help)

While thinking about this, I also realized that in the case of two tumors, one should consider maintaining two sets of positive centers, but the negative centers may need to be retrieved from the attention map(normal patches are distributed in both tumor cases).

**Comment by ChongQingNoSubway** [comment]
For now, NSCLC is still following the simple binary classification in our paper experiment setting. I have some ideas for solving this, which may take some time to validate. Thanks for reminding me.

**Comment by HHHedo** [comment]
Thanks for your help! Looking forward to it.
